const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { spawn } = require('node:child_process');
const server = spawn('python3', ['-m','http.server','8766','--bind','127.0.0.1'], {stdio:'ignore'});
const base = 'http://127.0.0.1:8766';
const getStatus = url => new Promise((resolve,reject) => require('node:http').get(url,r=>{r.resume();r.on('end',()=>resolve(r.statusCode));}).on('error',reject));
const output = process.env.HEADSHOTS_OUTPUT || '.github/review';
fs.mkdirSync(output,{recursive:true});
const tests=[];
(async () => {
  let browser;
  try {
    for(let i=0;i<50;i++){try{await getStatus(base);break;}catch{await new Promise(r=>setTimeout(r,100));}}
    browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || undefined,args:['--no-sandbox']});
    const context=await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1});
    const page=await context.newPage(); const errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
    await page.goto(base+'/headshots/',{waitUntil:'networkidle'});
    await page.evaluate(()=>document.fonts.ready);
    assert.equal(await page.locator('.portrait').count(),10);
    assert.equal(await page.locator('.filmstrip button').count(),10);
    assert.equal(await page.locator('#current-number').innerText(),'01');
    assert(await page.locator('body').evaluate(e=>e.classList.contains('enhanced')));
    await page.screenshot({path:output+'/headshots-desktop.png',fullPage:true});
    tests.push('Desktop: ten images loaded; 3D layout renders without errors.');
    for(let i=0;i<10;i++){await page.locator('#next').click();assert.equal(await page.locator('#current-number').innerText(),String((i+1)%10+1).padStart(2,'0'));}
    await page.locator('.stage').focus(); await page.keyboard.press('ArrowLeft');
    assert.equal(await page.locator('#current-number').innerText(),'10');
    await page.keyboard.press('Home');
    assert.equal(await page.locator('#current-number').innerText(),'01');
    await page.locator('.filmstrip button').nth(4).click();
    assert.equal(await page.locator('#current-number').innerText(),'05');
    tests.push('Navigation: all ten portraits, wrapping, keyboard arrows, Home, thumbnails.');
    await page.locator('.stage').focus(); await page.keyboard.press('Enter');
    assert(await page.locator('dialog').evaluate(e=>e.open));
    await page.keyboard.press('ArrowRight'); assert.match(await page.locator('#lightbox-label').innerText(),/^06/);
    await page.keyboard.press('Escape'); assert.equal(await page.locator('dialog').evaluate(e=>e.open),false);
    assert.equal(await page.evaluate(()=>document.activeElement.classList.contains('stage')),true);
    tests.push('Viewer: opens, navigates, closes with Escape, restores focus.');
    await page.locator('#grid-view').click();
    assert(await page.locator('body').evaluate(e=>e.classList.contains('grid-mode')));
    for(let i=0;i<10;i++)assert(await page.locator('.portrait').nth(i).isVisible());
    await page.screenshot({path:output+'/headshots-grid.png',fullPage:true});
    await page.locator('.portrait').nth(8).click();
    assert.match(await page.locator('#lightbox-label').innerText(),/^09/);await page.locator('.close-lightbox').click();
    await page.locator('#spatial-view').click();
    await page.locator('.filmstrip button').first().click();await page.waitForTimeout(800);
    const stage=await page.locator('.stage').boundingBox();
    await page.mouse.move(stage.x+stage.width/2,stage.y+stage.height/2);
    await page.mouse.down();await page.mouse.move(stage.x+stage.width/2-300,stage.y+stage.height/2,{steps:12});await page.mouse.up();
    assert.notEqual(await page.locator('#current-number').innerText(),'01');
    assert.equal(await page.locator('dialog').evaluate(e=>e.open),false);
    tests.push('All-ten grid, full-size grid selection, mouse drag without accidental viewer.');
    await page.locator('.filmstrip button').first().click(); await page.waitForTimeout(800);
    await page.setViewportSize({width:390,height:844}); await page.goto(base+'/headshots/',{waitUntil:'networkidle'}); await page.evaluate(()=>document.fonts.ready);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:output+'/headshots-mobile.png',fullPage:true});
    await page.locator('#next').click();assert.equal(await page.locator('#current-number').innerText(),'02');
    for(const width of [320,768,1024]) { await page.setViewportSize({width,height:900}); assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)); }
    tests.push('Responsive: 320, 390, 768, 1024, 1440 px without horizontal page overflow.');
    const touchContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
    const touch=await touchContext.newPage();await touch.goto(base+'/headshots/',{waitUntil:'networkidle'});
    const cdp=await touchContext.newCDPSession(touch);
    const b=await touch.locator('.stage').boundingBox();const x=240,y=b.y+b.height/2;
    await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
    for(let i=1;i<=10;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-i*17,y}]});
    await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touch.waitForTimeout(300);
    assert.notEqual(await touch.locator('#current-number').innerText(),'01');
    assert.equal(await touch.locator('dialog').evaluate(e=>e.open),false);
    tests.push('Mobile: real touch-event swipe changes portrait without accidental opening.');
    await touchContext.close();
    await page.emulateMedia({reducedMotion:'reduce'});await page.reload({waitUntil:'networkidle'});
    assert(await page.locator('body').evaluate(e=>e.classList.contains('grid-mode')));
    tests.push('Reduced motion defaults to a still grid.');
    const fallback=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
    const nojs=await fallback.newPage(); await nojs.goto(base+'/headshots/');
    assert.equal(await nojs.locator('.portrait').count(),10);
    for(let i=0;i<10;i++)assert(await nojs.locator('.portrait').nth(i).isVisible());
    tests.push('No JavaScript: all ten original image links remain accessible.');
    await fallback.close();
    const links=await page.locator('a[href]').evaluateAll(as=>as.map(a=>a.getAttribute('href')).filter(h=>!h.startsWith('mailto:')&&!h.startsWith('https:')));
    for(const href of new Set(links)){const url=new URL(href,base+'/headshots/');assert.equal(await getStatus(url),200,url.href);}
    assert.equal(errors.length,0,errors.join('\n'));
    tests.push('Local navigation and asset links return 200; no browser console errors or failed resources.');
    fs.writeFileSync(output+'/validation.json',JSON.stringify({result:'PASS',tests},null,2)+'\n');
    console.log(tests.map(t=>'PASS '+t).join('\n'));
  } finally {if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
